name: auto deployment with git-action

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: clone from github repository source
        uses: actions/checkout@v5

      - name: install JDK17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: add appplication yml
        run: |
          mkdir -p src/main/resources || true
          echo "${{secrets.APPLICATION_YML}}" > ./src/main/resources/application.yml
          cat ./src/main/resources/application.yml

      - name: build jar
        run: |
          chmod +x ./gradlew # 실행 권한 추가
          ./gradlew clean build  

      - name: rename, move jar to app.jar
        run: |
          pwd
          mv ./build/libs/*-SNAPSHOT.jar ./app.jar
          ls -al

      - name: send jar file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_KEY}}
          source: ./app.jar
          target: /home/ubuntu/prod/tobe

  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest

    steps:
      - name: stop running process and start new process
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_KEY}}
          script_stop: 'true'
          script: |
            sudo fuser --k -n tcp 8080 || true
            rm -rf /home/ubuntu/prod/cur || true
            mkdir -p /home/ubuntu/prod/cur
            cd home/ubuntu/prod/cur
            mv ../tobe/app.jar .
            sudo nohup java -jar app.jar > ./output.log 2>&1 &